### PR TITLE
Structural refactoring.

### LINKED ISSUE #19: Align file structure to better match best practices.
This is a drastically revised project structure.. but is much more in-line with other projects and will be easier to maintain in the long run. <strike>This may break some things because doing it amidst you doing other changes was hard to keep the branches in sync. If anything doesn't work, it can be easily fixed. </strike>  It's working fine.

@fdivitto, let me know if you are hesitant, i can elaborate further why it's nice to stick to what people know/expect, even if kind of scary moving things around so drastically.

screen shot 2016-01-27 at 6 16 30 pm

### PR DESCRIPTION
**Pull request by mralexgray**
lot's of file changes, but just because those damn sdk's are checked into this repo, per #18... this fixes #19.

### CODE REVIEW

**Comment by mralexgray** [comment]
notice `usage`...

`make`          builds in build/debug (untracked)
`make release`  builds (git tracked) bins for dist in build/release
`make clean`    cleans build directory, resets release to checked out bins

**Comment by mralexgray** [comment]
This also now fixes #18.  compiles and should merge/build AOK.  git submodule update is now in makefile, bu in case it doesn;t work on existing checkout, `git submodule update --init --recursive`, `git clean -fd`, and `make clean all`

**Comment by mralexgray** [comment]
ive tweaked and tested all the proposed changes at  `41adcd1`, above.  it'd prolly be easier to just check that out and go from there.

**Comment by mralexgray** [comment]
there are only 91 files in the project, total, at this commit. (including both versions of www)

**Comment by fdivitto** [comment]
What do you mean?

**Comment by mralexgray** [comment]
just easier to `git checkout master; git fetch --all; git merge 41adcd1` than to try to do it by hand...  you can always `git checkout anything` to go back to your master.  it solves stupid problems like `SDK` .> `sdk` which is hard to deal with by hand.

**Pull request closed without merging**
